name: peace_of_cake
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  permission_handler:
  shared_preferences: ^2.0.6
  hexcolor: ^2.0.4
  fluttertoast: ^8.0.8
  smooth_page_indicator: ^1.0.0+2
  settings_ui: ^2.0.2

  firebase_core: ^1.4.0
  firebase_auth: ^3.0.1
  cloud_firestore: ^2.4.0
  firebase_storage: ^10.0.1
  firebase_messaging: ^10.0.5

  flutter_sound: ^9.2.2
  audioplayers: ^0.19.1
  record_mp3: ^3.0.0

  agora_rtc_engine: ^5.1.0

  speech_to_text: ^5.3.0

  image_picker: ^0.8.5+3
  google_ml_kit: ^0.11.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true
  assets:
    - images/


